name: build

on: [push]

jobs:
  macOS:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: submodule
        run: git submodule update --init --recursive

      - name: cmake build
        run: mkdir build && cd build && cmake .. && make ScopeGUI

  Linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: submodule
        run: git submodule update --init --recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      - name: cmake build
        run: mkdir build && cd build && cmake .. && make ScopeGUI
