name: Windows

on: [push]

jobs:
  Windows:
    runs-on: windows-latest
    env:
      targetName: ScopeGUI
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Submodules
        run: git submodule update --init --recursive

      - name: CMake Build
        shell: powershell
        run: |
          $env:path=$env:path.Replace("C:\Program Files\Git", "HIDE_GIT")
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release .. -G "MinGW Makefiles"
          mingw32-make ScopeGUI
          Compress-Archive -Path ${{ env.targetName }}.exe ${{ env.targetName }}.zip

      - name: Make Release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ env.targetName }}.zip
          asset_name: ${{ env.targetName }}_${{ runner.os }}.zip
          tag: ${{ github.ref }}
          overwrite: true
